spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#        jdbc:
#          time_zone: Asia/Seoul
    show-sql: true

jwt:
  secret: 12345678901234567890123456789012
  token-valid-in-seconds: 86400 # 하루

#server:
#  port: 8081
